-- ==============================================================================
-- CORPUS RAG MASIVO Y EXHAUSTIVO - CLÍNICA DENTAL NECLATRONY
-- Base de Conocimiento Clínico para Agente RAG en Supabase
-- ==============================================================================

-- 1. Limpieza de datos preliminares para poblar el corpus exhaustivo
TRUNCATE TABLE public.clinica_knowledge;

-- 2. Inserción de Conocimiento Profundo por Bloques Temáticos

-- BLOQUE 1: ODONTOLOGÍA GENERAL Y PREVENTIVA
INSERT INTO public.clinica_knowledge (category, subcategory, title, content) VALUES
('TRATAMIENTO', 'General', 'Tartrectomía y Profilaxis Dental Profunda',
 'La limpieza dental profesional con ultrasonidos piezoeléctricos (tartrectomía) es un procedimiento profiláctico indoloro diseñado para eliminar sarro supragingival, placa bacteriana calcificada y manchas extrínsecas producidas por tabaco, café o té. Se realiza en los gabinetes 1 y 2. El protocolo dura entre 35 y 50 minutos e incluye: remoción mecánica de cálculo mediante puntas ultrasónicas refrigeradas, aeropulido con bicarbonato micronizado para manchas difíciles, pulido final con pasta profiláctica de flúor y aplicación tópica de barniz desensibilizante. Precio particular: 45 euros. Cobertura aseguradoras: Es un acto clínico 100% gratuito una vez al año para titulares de pólizas de Sanitas Dental, Adeslas Dental, Mapfre Caja Salud, DKV Seguros y Asisa. Se recomienda realizar una tartrectomía cada 6 a 12 meses para prevenir gingivitis y periodontitis.'),

('TRATAMIENTO', 'General', 'Obturaciones Dentales en Resina Composite (Empastes)',
 'El tratamiento de lesiones cariosas mediante obturación estética consiste en la eliminación del tejido dental desmineralizado e infectado y su posterior reconstrucción anatómica con resinas compuestas nanohíbridas fotopolimerizables con coincidencia tonal de la guía cromática VITA. Se realiza bajo anestesia local infiltrativa o tópica de benzocaína. Siempre se utiliza aislamiento absoluto con dique de goma para evitar la contaminación por saliva y garantizar una adhesión duradera. Precios según extensión anatómica: Obturación simple (una cara oclusal): 50 euros; Obturación compuesta (dos caras, ej. oclusomesial o oclusodistal): 60 euros; Reconstrucción compleja de gran volumen: 70 euros. Si la caries afecta la vitalidad pulpar pero no requiere endodoncia, se aplica un protector dentinopulpar a base de silicato cálcico (TheraCal) sin coste adicional. Garantía de 2 años sujeta a revisiones periódicas.'),

('TRATAMIENTO', 'General', 'Reconstrucciones Dentales con Poste de Fibra de Vidrio',
 'Indicadas en piezas dentales que han perdido más del 50% de su estructura coronal remanente debido a caries masivas o traumatismos, especialmente tras un tratamiento de conductos (endodoncia). El procedimiento consiste en cementar un perno intraradicular de fibra de vidrio de alta elasticidad (módulo similar a la dentina para evitar fracturas radiculares) con cemento de resina dual y modelar un muñón anatómico de composite de muñones. Precio: poste de fibra de vidrio 65 euros; reconstrucción de muñón 60 euros (total: 125 euros). Posteriormente se aconseja coronar la pieza con zirconio para asegurar su longevidad masticatoria.'),

('TRATAMIENTO', 'General', 'Sensibilidad Dental y Tratamientos Desensibilizantes',
 'La hipersensibilidad dentinaria ocurre cuando la dentina queda expuesta por retracción de encías, bruxismo o cepillado traumático, manifestándose con dolor agudo ante frío, calor, dulces o ácidos. En clínica aplicamos barnices de fluoruro de sodio al 5% y selladores tubulares con tecnología de fosfosilicato de calcio y glutaraldehído (Gluma Desensitizer) que ocluyen los túbulos dentinarios de forma inmediata. Precio por sesión en clínica: 25 euros por cuadrante. Recomendamos además pastas específicas con nitrato potásico y fluoruro de estaño y cepillos de filamentos cónicos ultrasuaves.');

-- BLOQUE 2: IMPLANTOLOGÍA Y REHABILITACIÓN ORAL AVANZADA
INSERT INTO public.clinica_knowledge (category, subcategory, title, content) VALUES
('TRATAMIENTO', 'Implantes', 'Implantes Dentales Unitarios de Titanio Osteointegrados',
 'Un implante dental es un tornillo de titanio puro de grado médico IV/V con tratamiento de superficie arenada y grabada al ácido (SLA) que sustituye la raíz de una pieza dental ausente, fusionándose biológicamente con el hueso alveolar mediante osteointegración. Se realiza en el gabinete quirúrgico 3 bajo anestesia local ambulatoria y campo estéril. Tiempo quirúrgico: 25 a 40 minutos por implante. Periodo de osteointegración: de 8 a 10 semanas en la mandíbula y de 12 a 14 semanas en el maxilar superior antes de colocar la prótesis definitiva. Precio orientativo: Fase quirúrgica (colocación del implante de titanio, tornillo de cierre, aditamentos protésicos y revisiones): 590 euros. Fase protésica (corona definitiva de zirconio monolítico sobre interfase de titanio): 480 euros. Total por pieza completa: 1.070 euros (financiable en 36 cuotas de 29,72 euros/mes sin intereses). Tasa de éxito clínico documentada en Neclatrony: 98,4%. Garantía por escrito del implante de titanio: 10 años.'),

('TRATAMIENTO', 'Implantes', 'Protocolo de Carga Inmediata y Dientes en un Día',
 'Técnica vanguardista que permite extraer una pieza deteriorada, colocar el implante dental y fijar una corona provisional de alta estética en la misma sesión clínica (en menos de 24 horas), evitando que el paciente pase meses desdentado o con prótesis removibles. Requiere una estabilidad primaria intraósea superior a 35 N/cm determinada mediante torque de inserción e ISQ (análisis de frecuencia de resonancia). Ideal para sectores anteriores (incisivos y caninos). Suplemento por prótesis provisional inmediata de PMMA fresado CAD/CAM: 150 euros.'),

('TRATAMIENTO', 'Implantes', 'Rehabilitaciones de Arcada Completa: All-on-4 y All-on-6',
 'Solución para pacientes edéntulos totales o con dentición terminal no recuperable. Consiste en colocar cuatro o seis implantes dentales estratégicamente distribuidos (con los implantes posteriores inclinados hasta 45 grados para aprovechar el remanente óseo y evitar el seno maxilar o el nervio dentario) y atornillar una prótesis completa híbrida de 12 dientes fijos el mismo día o en 48 horas. Precio orientativo cerrado: All-on-4 arcada completa con prótesis fija provisional y definitiva de zirconio sobre barra fresada: desde 5.800 euros por maxilar. Incluye cirugías, sedación consciente opcional con médico anestesista, implantes, revisiones y prótesis definitiva. Financiable hasta en 60 meses.'),

('TRATAMIENTO', 'Implantes', 'Cirugía de Elevación de Seno Maxilar y Regeneración Ósea',
 'Cuando un paciente carece de altura o grosor óseo en los sectores posteriores superiores debido a la pérdida prematura de molares y la neumatización del seno, se practica una elevación de seno maxilar. Puede ser técnica abierta (acceso por ventana lateral vestibular) o técnica cerrada atraumática (técnica de Summers mediante compactadores óseos a través del lecho del implante). Se rellena con hidroxiapatita bovina desproteinada (Bio-Oss) o fosfato tricálcico sintético combinado con membranas de colágeno porcino reabsorbible (Bio-Gide). Precio de elevación de seno con biomateriales: desde 350 euros en técnica cerrada hasta 650 euros en técnica abierta compleja. Tiempo de consolidación ósea previa a la carga: 6 meses.'),

('TRATAMIENTO', 'Implantes', 'Prótesis Fija de Zirconio Monolítico frente a Metal-Porcelana',
 'En la Clínica Neclatrony confeccionamos las coronas y puentes sobre implantes exclusivamente mediante diseño y fresado robótico digital CAD/CAM en zirconio translúcido multicapa. Ventajas frente al metal-cerámica tradicional: 100% biocompatible, ausencia total de bordes oscuros o grises en la encía con el paso de los años, nula corrosión galvánica, adhesión bacteriana significativamente menor (previniendo periimplantitis) y resistencia a la fractura superior a 1.200 MPa. Precio de corona unitaria sobre implante en zirconio: 480 euros.');

-- BLOQUE 3: ORTODONCIA CONVENCIONAL E INVISIBLE
INSERT INTO public.clinica_knowledge (category, subcategory, title, content) VALUES
('TRATAMIENTO', 'Ortodoncia', 'Ortodoncia Invisible con Alineadores Transparentes (Invisalign / Neclatrony Align)',
 'Tratamiento ortodóncico de máxima discreción mediante férulas termoplásticas transparentes de poliuretano multicapa patentado SmartTrack de 0,75 mm de espesor. Las férulas son removibles para comer y cepillarse los dientes, pero exigen un compromiso de uso de 22 horas diarias. Cada alineador efectúa micromovimientos dentales programados y se sustituye por el siguiente par cada 7 o 10 días según las indicaciones del Dr. Rodríguez en el consultorio 5. El tratamiento arranca con un estudio digital 3D completo: escaneado intraoral de alta precisión (sin pastas de silicona desagradables), fotografías clínicas y simulación tridimensional ClinCheck que permite al paciente ver el resultado final de su sonrisa antes de iniciar. Modalidades y Precios: Neclatrony Lite (hasta 14 alineadores para apiñamientos leves o recidivas, duración 4-7 meses): 2.400 euros; Neclatrony Comprehensive / Full (alineadores ilimitados para casos moderados y complejos con discrepancias esqueléticas, duración 12-24 meses): 3.600 a 3.900 euros. Ambos incluyen todas las revisiones, ataches estéticos de composite, refinamientos adicionales y el primer juego de retenedores finales Vivera.'),

('TRATAMIENTO', 'Ortodoncia', 'Brackets de Cristal de Zafiro y Brackets Metálicos',
 'La ortodoncia fija tradicional utiliza brackets cementados sobre la superficie vestibular de las piezas y arcos de aleaciones con memoria de forma (Níquel-Titanio y Acero). Brackets de Zafiro Monocristalino: Fabricados en zafiro puro pulido por ultrasonidos; son completamente transparentes, no absorben pigmentos (no se manchan con café, vino tinto ni tabaco) y mimetizan el color natural del esmalte. Precio completo: desde 2.200 euros con mensualidades fijas de 75 euros/mes. Brackets Metálicos de Baja Fricción: Máxima resistencia y efectividad mecánica en casos con severas discrepancias oclusales. Precio: desde 1.800 euros con mensualidades fijas de 65 euros/mes. Duración promedio de tratamiento: entre 14 y 22 meses con revisiones cada 4 a 6 semanas.'),

('TRATAMIENTO', 'Ortodoncia', 'Fase de Retención Final y Retenedores Fijos y Removibles',
 'Al retirar los brackets o terminar los alineadores, el hueso y ligamento periodontal requieren estabilización obligatoria para evitar la recidiva ortodóncica (que los dientes vuelvan a moverse a su posición original). El protocolo estándar en Neclatrony combina doble retención: 1) Retención fija lingual inferior: alambre trenzado de acero quirúrgico adherido con composite fluido por la cara interna de canino a canino (totalmente invisible y cómodo); 2) Férulas de retención nocturnas transparentes Essix / Vivera para arcada superior e inferior. Precio del set de retención completa si no está incluido en el tratamiento: 180 euros.');

-- BLOQUE 4: CIRUGÍA ORAL Y MAXILOFACIAL
INSERT INTO public.clinica_knowledge (category, subcategory, title, content) VALUES
('TRATAMIENTO', 'Cirugía', 'Extracción Quirúrgica de Muelas del Juicio (Terceros Molares / Cordales)',
 'La exodoncia de terceros molares está indicada ante cordales impactados o semi-incluidos, episodios repetidos de pericoronaritis (infección e inflamación de la encía pericoronaria), caries no tratables en el segundo o tercer molar, formación de quistes foliculares o apiñamiento dental anteroinferior. La intervención la realiza el Dr. Sánchez o el Dr. Fernández en los gabinetes quirúrgicos 4 o 6 bajo anestesia local troncular al nervio dentario inferior y lingual. Se complementa con radiografía panorámica digital y estudio tomográfico 3D (CBCT) si el molar tiene proximidad íntima con el conducto del nervio dentario para eliminar cualquier riesgo de parestesia. En molares con retención ósea se efectúa ostectomía y odontosección con instrumental rotatorio o piezoeléctrico para una extracción atraumática. Precios: Extracción simple de cordal erupcionado: 90 euros; Extracción quirúrgica compleja de cordal incluido con sutura reabsorbible: 140 a 160 euros.'),

('TRATAMIENTO', 'Cirugía', 'Frenectomías Linguales y Labiales con Láser Diodo',
 'Corrección quirúrgica de frenillos labiales hipertróficos (que provocan diastemas o separaciones interincisivas antiestéticas) o frenillos linguales cortos (anquiloglosia que dificulta el habla, la lactancia o el movimiento lingual). En Neclatrony utilizamos tecnología de láser diodo quirúrgico de 810 nm. Ventajas: corte de máxima precisión sin sangrado gracias a la fotocoagulación instantánea, ausencia de dolor postoperatorio, sin necesidad de suturas convencionales y cicatrización completa en menos de 7 días. Precio de la intervención con láser: 120 euros.'),

('TRATAMIENTO', 'Cirugía', 'Fenestración Quirúrgica de Caninos Incluidos',
 'Procedimiento quirúrgico-ortodóncico que consiste en abrir una ventana en la encía y hueso sobre un canino definitivo que no ha erupcionado espontáneamente y permanece alojado en el paladar o maxilar. Se cementa un botón ortodóncico con cadeneta de tracción para que el ortodoncista guíe gradualmente la pieza hacia su posición correcta en la arcada. Precio: 160 euros.');

-- BLOQUE 5: ENDODONCIA Y ODONTOLOGÍA CONSERVADORA
INSERT INTO public.clinica_knowledge (category, subcategory, title, content) VALUES
('TRATAMIENTO', 'Endodoncia', 'Terapia de Conductos y Endodoncia Rotatoria Mecanizada',
 'Tratamiento comúnmente denominado "matar el nervio". Consiste en la extirpación aséptica del tejido pulpar inflamado o necrosado del interior de la cámara pulpar y conductos radiculares, la desinfección química exhaustiva y el sellado hermético tridimensional con gutapercha termoplástica. Se practica ante pulpitis irreversibles por caries profundas, traumatismos o necrosis bacteriana. En la clínica empleamos motores de endodoncia de última generación con cinemática rotatoria continua y reciprocante (WaveOne Gold / ProTaper Ultimate) con aleaciones de níquel-titanio térmicamente tratadas que se adaptan a las curvaturas anatómicas de la raíz, localizadores apicales electrónicos de precisión micrométrica e irrigación ultrasónica activada con hipoclorito sódico al 5,25%. Precios: Endodoncia unirradicular (incisivos y caninos con 1 conducto): 120 euros; Endodoncia birradicular (premolares con 2 conductos): 145 euros; Endodoncia multirradicular (molares con 3 o 4 conductos complejos): 180 euros. Los precios incluyen radiografías periapicales digitales de conductometría y conometría y medicación antibacteriana intermedia si la infección es supurativa.'),

('TRATAMIENTO', 'Endodoncia', 'Retratamiento Endodóntico de Conductos',
 'Procedimiento indicado cuando una endodoncia previa fracasa, provocando dolor persistente o una lesión periapical (quiste o granuloma) debido a bacterias residuales, conductos omitidos o sellado deficiente. Implica desobturar el material previo, localizar conductos accesorios mediante magnificación óptica, desinfectar y volver a sellar. Precio: Suplemento de 40 euros sobre el coste de la endodoncia estándar.');

-- BLOQUE 6: PERIODONCIA Y SALUD DE ENCÍAS
INSERT INTO public.clinica_knowledge (category, subcategory, title, content) VALUES
('TRATAMIENTO', 'Periodoncia', 'Raspado y Alisado Radicular por Cuadrante (Curetajes)',
 'Tratamiento fundamental para la periodontitis (piorrea), enfermedad inflamatoria crónica de origen bacteriano que destruye el ligamento periodontal y el hueso alveolar de soporte, provocando movilidad y pérdida de piezas dentales. El procedimiento se divide en sesiones por cuadrantes bajo anestesia local. Se utilizan ultrasonidos para el sarro superficial y curetas específicas Gracey para desbridar y alisar la superficie de la raíz dental dentro de las bolsas periodontales, eliminando cálculo subgingival y toxinas bacterianas. Incluye sondaje periodontal computarizado previo con registro de profundidades de bolsa, sangrado al sondaje y retracciones, irrigación con digluconato de clorhexidina al 0,2% y reevaluación periodontal exhaustiva a las 6 semanas. Precio: 65 euros por cuadrante (boca completa en 4 cuadrantes: 260 euros). Mantenimientos periodontales semestrales: 50 euros.'),

('TRATAMIENTO', 'Periodoncia', 'Cirugía Mucogingival e Injertos de Encía',
 'Intervención de microcirugía periodontal destinada a cubrir raíces dentales descubiertas por recesiones gingivales severas que generan hipersensibilidad o compromiso estético. Se toma un microinjerto de tejido conectivo del paladar del propio paciente y se trasplanta al lecho receptor mediante técnicas de túnel mínimamente invasivas. Precio por lecho quirúrgico: 280 euros.');

-- BLOQUE 7: ESTÉTICA DENTAL Y DISEÑO DE SONRISA
INSERT INTO public.clinica_knowledge (category, subcategory, title, content) VALUES
('TRATAMIENTO', 'Estética', 'Blanqueamiento Dental Combinado en Clínica y Domicilio',
 'El sistema blanqueador más seguro, eficaz y duradero del mercado odontológico. Combina una fase clínica de activación rápida en sillón dental y una fase domiciliaria de estabilización: 1) Sesión clínica en gabinete de 45 minutos con peróxido de hidrógeno al 35% fotoactivado con lámpara de luz fría LED de longitud de onda específica, protegiendo previamente los tejidos blandos con barrera gingival fotopolimerizable; 2) Tratamiento ambulatorio durante 15 noches consecutivas aplicando gel de peróxido de carbamida al 16% mediante férulas transparentes flexibles hechas a medida en el laboratorio. Aclara entre 4 y 7 tonos según la escala cromática dental VITA. Precio promocional del tratamiento completo con férulas y kit de gel: 290 euros. Requisito obligatorio: tener la boca libre de caries activas y una limpieza bucal reciente (últimos 30 días).'),

('TRATAMIENTO', 'Estética', 'Carillas de Porcelana Disilicato de Litio (IPS e.max)',
 'Láminas cerámicas de alta resistencia y translucidez con un grosor ultrafino de entre 0,3 y 0,5 mm que se cementan adhesivamente sobre la cara vestibular de los dientes frontales para modificar forma, color, textura o corregir pequeñas malposiciones y diastemas. El disilicato de litio IPS e.max ofrece un comportamiento lumínico idéntico al esmalte natural y una estabilidad cromática indefinida (no se tiñen nunca). Precio por pieza: 320 euros. Incluye diseño digital de sonrisa (DSD), mock-up o prueba estética en boca previa, tallado conservador mínimamente invasivo y carillas provisionales.'),

('TRATAMIENTO', 'Estética', 'Férulas de Descarga Neuromiorrelajantes tipo Michigan para Bruxismo',
 'El bruxismo (hábito involuntario de apretar o rechinar los dientes durante el sueño o en momentos de estrés) provoca desgaste acelerado del esmalte dental, fracturas de empastes, dolor en los músculos maseteros y disfunción dolorosa en la articulación temporomandibular (ATM) con chasquidos y dolores de cabeza matutinos. La férula de Michigan es un dispositivo intraoral rígido de resina acrílica transparente dura de 2-3 mm de grosor, confeccionada a medida mediante escaneado o modelos montados en articulador semiajustable. Diseñada con planos guía y desoclusión canina que desconecta el reflejo neuromuscular de apretamiento nocturno. Precio: 210 euros (incluye toma de registros, entrega, ajuste oclusal en clínica con papel de articular y revisiones periódicas de equilibrado).');

-- BLOQUE 8: CONDICIONES COMERCIALES, FINANCIACIÓN Y FORMAS DE PAGO
INSERT INTO public.clinica_knowledge (category, subcategory, title, content) VALUES
('PRECIOS_PAGOS', 'Financiación', 'Planes de Financiación a Medida y Condiciones Crediticias',
 'En la Clínica Dental Neclatrony facilitamos el acceso a cualquier tratamiento dental mediante acuerdos preferentes con las principales entidades financieras de crédito al consumo (Santander Consumer Finance y Cetelem). Opciones disponibles: 1) Financiación hasta en 36 meses sin intereses: TIN 0%, TAE 0% asumiendo la clínica los gastos de apertura y comisiones bancarias para tratamientos cuyo presupuesto supere los 1.000 euros (ej. implantes dentales, ortodoncia invisible o rehabilitaciones fijas); 2) Financiación extendida hasta en 60 meses con interés preferente para importes elevados. Requisitos para tramitación en recepción: DNI/NIE original en vigor, justificante bancario de titularidad con código IBAN y última nómina (trabajadores por cuenta ajena) o última declaración de la renta/recibo de autónomo (autónomos) o justificante de pensión. La aprobación bancaria se gestiona de forma digital y telemática en el mostrador en menos de 15 minutos.'),

('PRECIOS_PAGOS', 'Pagos', 'Medios de Pago y Normativa de Pagos en Efectivo',
 'Medios de pago aceptados en la clínica: 1) Tarjetas de débito y crédito físicas o contactless en datáfono de recepción (Visa, Mastercard, Maestro, American Express); 2) Bizum profesional corporativo directo al número oficial de la clínica; 3) Transferencia bancaria directa antes de la colocación de prótesis o cirugías mayores; 4) Efectivo metálico en recepción física, sujeto estrictamente a la Ley 11/2021 de prevención del fraude fiscal que limita los pagos en metálico a un importe máximo de 1.000 euros por operación o paciente en transacciones donde interviene un profesional o empresa. Presupuestos superiores deben abonarse por medios electrónicos o financiación.'),

('PRECIOS_PAGOS', 'Garantías', 'Política Oficial de Garantías por Escrito en Neclatrony',
 'Todos los tratamientos realizados en la clínica cuentan con garantía formal por escrito: 1) Implantes dentales de titanio: garantía de 10 años en el tornillo de titanio y aditamentos quirúrgicos ante cualquier eventualidad de pérdida de osteointegración (sustitución gratuita del implante); 2) Coronas y puentes de zirconio o metal-cerámica: 5 años de garantía ante fracturas de material; 3) Obturaciones de composite: 2 años de garantía. Requisito de validez de la garantía: el paciente debe acudir puntualmente a las revisiones clínicas periódicas anuales pautadas y mantener unos niveles adecuados de higiene bucodental certificados por el cuadro médico.');

-- BLOQUE 9: ASEGURADORAS Y CONCIERTOS DENTALES
INSERT INTO public.clinica_knowledge (category, subcategory, title, content) VALUES
('SEGUROS', 'Sanitas', 'Condiciones y Coberturas con Sanitas Dental',
 'La Clínica Dental Neclatrony es centro concertado preferente del Cuadro Médico de Sanitas Dental. Beneficios directos para asegurados de pólizas Sanitas Dental Milenium y Sanitas Salud: Actos 100% gratuitos incluidos en póliza: consulta inicial de valoración odontológica, ortopantomografía digital panorámica, radiografías periapicales de diagnóstico, una tartrectomía (limpieza dental completa con ultrasonidos) por año natural y extracciones de dientes de leche en niños. Resto de tratamientos: baremo concertado Sanitas con descuentos de entre el 30% y el 40% sobre los precios de tarifa privada de particular (ej. tarifas reducidas en empastes, endodoncias y ortodoncia). Para validar el servicio basta con presentar la tarjeta digital Sanitas desde la app móvil en recepción.'),

('SEGUROS', 'Adeslas', 'Condiciones y Coberturas con Adeslas Dental',
 'Centro concertado con SegurCaixa Adeslas (pólizas Adeslas Dental Max, Dental Total y colectivos corporativos). Los asegurados disponen de gratuidad absoluta en revisiones semestrales, radiología digital diagnóstica intraoral y extraoral y una limpieza bucal al año. Los tratamientos de ortodoncia, cirugía e implantes se facturan bajo el riguroso baremo de franquicias fijas concertadas de Adeslas Dental, con un ahorro medio estimado del 35% respecto a tarifas de particular. La validación se ejecuta en el acto mediante el lector de tarjetas del TPV virtual de Adeslas.'),

('SEGUROS', 'Mapfre_DKV_Asisa', 'Condiciones con Mapfre Caja Salud, DKV Seguros y Asisa Dental',
 'La clínica mantiene conciertos vigentes con Mapfre Caja Salud (red dental), DKV Seguros (DKV Dentisalud) y Asisa Dental. Todos los asegurados de estas entidades disfrutan de consulta y revisión diagnóstica gratuita, radiografías y una profilaxis dental anual sin coste. El resto de tratamientos restauradores, periodontales o quirúrgicos se liquidan conforme a los respectivos baremos vigentes de cada aseguradora.'),

('SEGUROS', 'Particulares', 'Ventajas para Pacientes Particulares sin Seguro Dental',
 'Para aquellos pacientes que no disponen de ninguna póliza o mutua privada de salud dental, la Clínica Neclatrony ofrece como cortesía la primera visita diagnóstica integral totalmente gratuita, la cual incluye exploración clínica visual completa por odontólogo especialista, toma de ortopantomografía digital panorámica de alta definición y entrega de plan de tratamiento personalizado con presupuesto cerrado sin compromiso de contratación.');

-- BLOQUE 10: PROTOCOLOS PREOPERATORIOS, POSQUIRÚRGICOS Y URGENCIAS
INSERT INTO public.clinica_knowledge (category, subcategory, title, content) VALUES
('PROTOCOLO', 'Preoperatorio', 'Instrucciones y Pautas Previas a Cirugías e Implantes',
 'Instrucciones obligatorias para pacientes programados para cirugías de implantes o extracciones molares: 1) Alimentación: Si la intervención es bajo anestesia local estándar, desayunar o almorzar con normalidad unas 2 horas antes (no acudir en ayunas para evitar bajadas de glucosa o mareos vasovagales). Si la cirugía se realiza con sedación consciente endovenosa coordinada por médico anestesista, se exige ayuno estricto absoluto de sólidos y líquidos durante las 6 horas previas; 2) Medicación profiláctica: Si el doctor prescribió antibiótico previo, tomar amoxicilina 2 gramos (o clindamicina 600 mg en caso de alergia acreditada a penicilinas) exactamente 1 hora antes de la intervención quirúrgica; 3) Indumentaria: Acudir con ropa holgada y cómoda, sin maquillaje, sin pintalabios ni joyas metálicas en cabeza o cuello; 4) Acompañante: Se aconseja acudir acompañado de un adulto responsable en cirugías complejas.'),

('PROTOCOLO', 'Postoperatorio', 'Protocolo Médico Posquirúrgico tras Extracción o Implante',
 'Normas médicas esenciales para garantizar una cicatrización adecuada y prevenir complicaciones posoperatorias (como alveolitis seca o infecciones): 1) Hemostasia: Morder firmemente la gasa estéril colocada sobre la herida durante 30 a 45 minutos continuos. Si al retirarla persiste el sangrado, colocar una gasa limpia doblada o una bolsita de té negro humedecida y volver a morder otros 30 minutos; 2) Enjuagues y escupir: TOTALMENTE PROHIBIDO enjuagarse la boca, escupir o utilizar pajitas para beber durante las primeras 24 horas. Escupir crea presión negativa en la cavidad oral que desaloja el coágulo sanguíneo recién formado, reactivando la hemorragia y dejando el hueso expuesto; a partir de las 24 horas, realizar enjuagues muy suaves con clorhexidina al 0,12% tres veces al día tras las comidas; 3) Crioterapia: Aplicar frío local externo (bolsa de hielo envuelta en paño) sobre la piel de la mejilla durante 10 minutos seguidos, descansando otros 10 minutos, durante las primeras 6 horas post-cirugía para limitar la inflamación y el edema; 4) Dieta: Consumir únicamente alimentos blandos, tibios o fríos durante las primeras 48 horas (yogures, gelatinas, helados sin tropezones, purés y caldos tibios); evitar alimentos crujientes, picantes o semillas; 5) Tabaco y Alcohol: ESTRICTAMENTE PROHIBIDO fumar durante un mínimo de 72 horas (idealmente 7 días). El calor y los componentes tóxicos del tabaco multiplican por 5 el riesgo de infección y el fracaso de la osteointegración de implantes; 6) Ejercicio físico: Evitar deportes intensos, gimnasio y cargar peso durante al menos 3 a 5 días; 7) Descanso: Dormir la primera noche con la cabeza ligeramente incorporada mediante dos almohadas para disminuir la presión vascular cefálica; 8) Analgesia: Tomar la medicación analgésica y antiinflamatoria pautada (ibuprofeno 600 mg alternado con paracetamol 1 g cada 4 u 8 horas) antes de que se extinga por completo el efecto anestésico local.'),

('PROTOCOLO', 'Urgencias', 'Protocolo de Urgencias: Traumatismo Dental y Avulsión Dental',
 'Actuación crítica ante la caída o expulsión completa de un diente definitivo por un golpe o caída (avulsión dental): El factor tiempo es determinante para la supervivencia del diente. 1) Localizar la pieza dental y sujetarla SIEMPRE por la corona (la parte blanca visible). NUNCA tocar, raspar ni frotar la raíz dental, ya que contiene las células vivas del ligamento periodontal imprescindibles para que el diente vuelva a prender en el alveolo; 2) Si el diente está sucio por tierra, enjuagarlo durante un máximo de 5 segundos bajo un chorro suave de leche o suero salino fisiológico (NUNCA usar jabón ni cepillarlo); 3) Si el paciente o acompañante se siente capaz, reimplantar el diente inmediatamente en el hueco del alveolo de la boca y morder un pañuelo para mantenerlo sujeto; 4) Si no es posible reimplantarlo, transportar el diente sumergido en un recipiente con LECHE ENTERA, suero fisiológico o, como último recurso, en el interior de la boca del paciente (entre la mejilla y las encías); NUNCA transportarlo en agua ni dejarlo secar en una servilleta; 5) Acudir de urgencia a la Clínica Neclatrony en MENOS DE 60 MINUTOS. Si se actúa antes de 1 hora, la probabilidad de salvar y conservar el diente supera el 85%.'),

('PROTOCOLO', 'Urgencias', 'Protocolo de Urgencias: Dolor Agudo Pulsátil y Flemón con Inflamación',
 'Ante dolor dental severo, continuo y pulsátil que no cede con analgésicos habituales, acompañado o no de inflamación facial evidente (flemón o absceso periapical): 1) Acudir de inmediato a la clínica para exploración y apertura de cámara pulpar para drenaje de la presión bacteriana acumulada; 2) No aplicar calor local nunca sobre la mejilla inflamada (el calor expande la infección bacteriana y acelera la celulitis facial); aplicar siempre frío externo; 3) Mantener la posición sentada o semisentada (tumbarse en la cama incrementa la presión sanguínea en la cabeza y agrava el dolor); 4) No colocar aspirinas ni alcohol directamente sobre la encía inflamada, ya que provoca quemaduras químicas severas en la mucosa; 5) Teléfono de urgencias de la clínica disponible 24h para pacientes citados: +34 933 394 358.');

-- 3. Verificación de Inserción
SELECT category, subcategory, COUNT(*) AS total_documentos 
FROM public.clinica_knowledge 
GROUP BY category, subcategory 
ORDER BY category;
